WITH LASTDAYMONTH AS(
 SELECT DATE_TRUNC (LOAD_DT, MONTH) AS MONTH, MAX(LOAD_DT) AS LASTDAY
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.cwc_jam_dna_fullmonth_202202` 
 WHERE org_cntry = "Jamaica" 
 GROUP BY MONTH
),
BOCLOSINGBASE AS(
SELECT DISTINCT MONTH, LASTDAY, act_acct_cd as RGUBO
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.cwc_jam_dna_fullmonth_202202` t
INNER JOIN LASTDAYMONTH l ON l.LASTDAY = t.load_dt AND DATE_TRUNC (t.LOAD_DT, MONTH) = l.MONTH
WHERE org_cntry = "Jamaica" AND (fi_outst_age < 90 OR fi_outst_age IS NULL) AND
ACT_CUST_TYP_NM IN ('Browse & Talk HFONE', 'Residence', 'Standard') AND ACT_ACCT_STAT IN ('B','D','P','SN','SR','T','W')
AND pd_mix_nm IN ('BO+VO+TV', 'BO+VO', 'BO', 'BO+TV')
GROUP BY MONTH, act_acct_cd, LASTDAY
),
TVCLOSINGBASE AS(
  SELECT DISTINCT MONTH, LASTDAY, act_acct_cd as RGUTV
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.cwc_jam_dna_fullmonth_202202` t
INNER JOIN LASTDAYMONTH l ON l.LASTDAY = t.load_dt AND DATE_TRUNC (t.LOAD_DT, MONTH) = l.MONTH
WHERE org_cntry = "Jamaica" AND (fi_outst_age < 90 OR fi_outst_age IS NULL) AND
ACT_CUST_TYP_NM IN ('Browse & Talk HFONE', 'Residence', 'Standard') AND ACT_ACCT_STAT IN ('B','D','P','SN','SR','T','W')
AND pd_mix_nm IN ('VO+TV', 'BO+VO+TV', 'TV', 'BO+TV')
GROUP BY MONTH, act_acct_cd, LASTDAY
),
VOCLOSINGBASE AS(
  SELECT DISTINCT MONTH, LASTDAY, act_acct_cd as RGUVO
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.cwc_jam_dna_fullmonth_202202` t
INNER JOIN LASTDAYMONTH l ON l.LASTDAY = t.load_dt AND DATE_TRUNC (t.LOAD_DT, MONTH) = l.MONTH
WHERE org_cntry = "Jamaica" AND (fi_outst_age < 90 OR fi_outst_age IS NULL) AND
ACT_CUST_TYP_NM IN ('Browse & Talk HFONE', 'Residence', 'Standard') AND ACT_ACCT_STAT IN ('B','D','P','SN','SR','T','W')
AND pd_mix_nm IN ('VO+TV', 'BO+VO+TV', 'VO', 'BO+VO')
GROUP BY MONTH, act_acct_cd, LASTDAY 
),
BOCLOSINGBASEDATES AS(
  SELECT MONTH, LASTDAY, COUNT (DISTINCT RGUBO) AS CLOSING_BASE_BO_RGUS
  FROM BOCLOSINGBASE
  GROUP BY MONTH,LASTDAY
  ORDER BY MONTH, LASTDAY  
),
TVCLOSINGBASEDATES AS(
  SELECT MONTH, LASTDAY, COUNT (DISTINCT RGUTV) AS CLOSING_BASE_TV_RGUS
  FROM TVCLOSINGBASE
  GROUP BY MONTH,LASTDAY
  ORDER BY MONTH, LASTDAY
),
VOCLOSINGBASEDATES AS(
  SELECT MONTH, LASTDAY, COUNT (DISTINCT RGUVO) AS CLOSING_BASE_VO_RGUS
  FROM VOCLOSINGBASE
  GROUP BY MONTH,LASTDAY
  ORDER BY MONTH, LASTDAY
)
SELECT b.MONTH, b.LASTDAY, CLOSING_BASE_BO_RGUS, CLOSING_BASE_TV_RGUS, CLOSING_BASE_VO_RGUS, (CLOSING_BASE_BO_RGUS + CLOSING_BASE_TV_RGUS + CLOSING_BASE_VO_RGUS) as TOTALRGUS
FROM BOCLOSINGBASEDATES b 
INNER JOIN TVCLOSINGBASEDATES t ON b.MONTH = t.MONTH AND b.LASTDAY = t.LASTDAY 
INNER JOIN VOCLOSINGBASEDATES v ON b.MONTH = V.MONTH AND b.LASTDAY = v.LASTDAY
GROUP BY MONTH,LASTDAY,  CLOSING_BASE_BO_RGUS, CLOSING_BASE_TV_RGUS, CLOSING_BASE_VO_RGUS
ORDER BY MONTH, LASTDAY
