WITH MONTHDATES AS(
 SELECT DATE_TRUNC (LOAD_DT, MONTH) AS MONTH, LOAD_DT AS MONTHDATE
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.cwc_jam_dna_fullmonth_202202` 
 WHERE org_cntry = "Jamaica" 
 GROUP BY MONTH, load_dt
),
BOCLOSINGBASE AS(
SELECT DISTINCT MONTH, MONTHDATE, act_acct_cd as RGUBO
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.cwc_jam_dna_fullmonth_202202` t
INNER JOIN MONTHDATES l ON l.MONTHDATE = t.load_dt AND DATE_TRUNC (t.LOAD_DT, MONTH) = l.MONTH
WHERE org_cntry = "Jamaica" AND (fi_outst_age < 90 OR fi_outst_age IS NULL) AND
ACT_CUST_TYP_NM IN ('Browse & Talk HFONE', 'Residence', 'Standard') AND ACT_ACCT_STAT IN ('B','D','P','SN','SR','T','W')
AND pd_mix_nm IN ('BO+VO+TV', 'BO+VO', 'BO', 'BO+TV')
GROUP BY MONTH, act_acct_cd, MONTHDATE
),
TVCLOSINGBASE AS(
  SELECT DISTINCT MONTH, MONTHDATE, act_acct_cd as RGUTV
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.cwc_jam_dna_fullmonth_202202` t
INNER JOIN MONTHDATES l ON l.MONTHDATE = t.load_dt AND DATE_TRUNC (t.LOAD_DT, MONTH) = l.MONTH
WHERE org_cntry = "Jamaica" AND (fi_outst_age < 90 OR fi_outst_age IS NULL) AND
ACT_CUST_TYP_NM IN ('Browse & Talk HFONE', 'Residence', 'Standard') AND ACT_ACCT_STAT IN ('B','D','P','SN','SR','T','W')
AND pd_mix_nm IN ('VO+TV', 'BO+VO+TV', 'TV', 'BO+TV')
GROUP BY MONTH, act_acct_cd, MONTHDATE
),
VOCLOSINGBASE AS(
  SELECT DISTINCT MONTH, MONTHDATE, act_acct_cd as RGUVO
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.cwc_jam_dna_fullmonth_202202` t
INNER JOIN MONTHDATES l ON l.MONTHDATE = t.load_dt AND DATE_TRUNC (t.LOAD_DT, MONTH) = l.MONTH
WHERE org_cntry = "Jamaica" AND (fi_outst_age < 90 OR fi_outst_age IS NULL) AND
ACT_CUST_TYP_NM IN ('Browse & Talk HFONE', 'Residence', 'Standard') AND ACT_ACCT_STAT IN ('B','D','P','SN','SR','T','W')
AND pd_mix_nm IN ('VO+TV', 'BO+VO+TV', 'VO', 'BO+VO')
GROUP BY MONTH, act_acct_cd, MONTHDATE 
),
BOCLOSINGBASEDATES AS(
  SELECT MONTH, MONTHDATE, COUNT (DISTINCT RGUBO) AS CLOSING_BASE_BO_RGUS
  FROM BOCLOSINGBASE
  GROUP BY MONTH,MONTHDATE
  ORDER BY MONTH, MONTHDATE  
),
TVCLOSINGBASEDATES AS(
  SELECT MONTH, MONTHDATE, COUNT (DISTINCT RGUTV) AS CLOSING_BASE_TV_RGUS
  FROM TVCLOSINGBASE
  GROUP BY MONTH,MONTHDATE
  ORDER BY MONTH, MONTHDATE
),
VOCLOSINGBASEDATES AS(
  SELECT MONTH, MONTHDATE, COUNT (DISTINCT RGUVO) AS CLOSING_BASE_VO_RGUS
  FROM VOCLOSINGBASE
  GROUP BY MONTH,MONTHDATE
  ORDER BY MONTH, MONTHDATE
)
SELECT b.MONTH, b.MONTHDATE, CLOSING_BASE_BO_RGUS, CLOSING_BASE_TV_RGUS, CLOSING_BASE_VO_RGUS, (CLOSING_BASE_BO_RGUS + CLOSING_BASE_TV_RGUS + CLOSING_BASE_VO_RGUS) as TOTALRGUS
FROM BOCLOSINGBASEDATES b 
INNER JOIN TVCLOSINGBASEDATES t ON b.MONTH = t.MONTH AND b.monthdate = t.monthdate 
INNER JOIN VOCLOSINGBASEDATES v ON b.MONTH = V.MONTH AND b.monthdate = v.monthdate
GROUP BY MONTH,MONTHDATE,  CLOSING_BASE_BO_RGUS, CLOSING_BASE_TV_RGUS, CLOSING_BASE_VO_RGUS
ORDER BY MONTH, MONTHDATE
